@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_LEFT_RIGHT()

Person(user, "User")
System(system, "api-loan")
SystemDb(db, "Banco Sql")

Rel(user, system, "Preenche dados para simulacao")



Rel(system, db, "Insere resultado da simulacao")

@enduml
